# Generated by Django 5.2.5 on 2025-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/d6.jpg', null=True, upload_to='profile/', verbose_name='avatar'),
        ),
    ]
