# Generated by Django 5.2.5 on 2025-08-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_phone'),
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='products.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='accounts.Favorite', to='products.product', verbose_name='Избранные товары'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['profile', 'product'], name='accounts_fa_profile_71b455_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['created_at'], name='accounts_fa_created_1265f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'product')},
        ),
    ]
