services:
  db:
    image: postgres:14
    container_name: gy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gy_db
      POSTGRES_USER: gy_user
      POSTGRES_PASSWORD: gy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: ${DOCKERHUB_USERNAME}/gy-web:latest
    container_name: gy_web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /var/www/gy/static:/app/static
      - /var/www/gy/media:/app/media
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application
          --bind 0.0.0.0:8000
          --workers 4
          --timeout 120
          --access-logfile - 
          --error-logfile -"

volumes:
  postgres_data:
