version: "3.9"

services:
  db:
    image: postgres:14
    container_name: gy_postgres
    restart: always
    environment:
      POSTGRES_DB: gy_db
      POSTGRES_USER: gy_user
      POSTGRES_PASSWORD: gy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: ${DOCKERHUB_USERNAME}/gy-web:latest
    container_name: gy_web
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - /var/www/east-mosaic/gunicorn.sock:/gunicorn.sock
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application
             --bind unix:/gunicorn.sock
             --workers 4
             --timeout 120
             --access-logfile - 
             --error-logfile -"

volumes:
  postgres_data:
  static_data:
  media_data:
