# Generated by Django 5.2.5 on 2025-09-01 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79991234567 (10–15 цифр).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('topic', models.CharField(choices=[('order', 'Оформление заказа'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('exchange', 'Возврат и обмен'), ('other', 'Другое')], max_length=20, verbose_name='Тематика обращения')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('policy_agreed', models.BooleanField(default=False, verbose_name='Согласие с офертой/политикой')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='Согласие на рассылку')),
                ('page_url', models.URLField(blank=True, verbose_name='Страница отправки')),
                ('locale', models.CharField(blank=True, max_length=10, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Контактная заявка',
                'verbose_name_plural': 'Контактные заявки',
                'ordering': ('-created_at',),
            },
        ),
    ]
