# Generated by Django 5.2.5 on 2025-08-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Контакты и соцсети',
                'verbose_name_plural': 'Контакты и соцсети',
            },
        ),
    ]
