# Generated by Django 5.2.5 on 2025-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontacts',
            name='phone2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Второй Телефон'),
        ),
    ]
