# Generated by Django 5.2.5 on 2025-09-01 12:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
