name: build-and-push

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          IMG="${DOCKERHUB_USERNAME}/gy-web"
          echo "img=${IMG}" >> $GITHUB_OUTPUT
          echo "sha=${IMG}:${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "latest=${IMG}:latest" >> $GITHUB_OUTPUT
          echo "branch=${IMG}:branch-${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.sha }}
            ${{ steps.vars.outputs.latest }}
            ${{ steps.vars.outputs.branch }}
          cache-from: type=registry,ref=${{ steps.vars.outputs.img }}:buildcache
          cache-to: type=registry,ref=${{ steps.vars.outputs.img }}:buildcache,mode=max

      - name: Tag release (if tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx imagetools create \
            -t ${{ steps.vars.outputs.img }}:${GITHUB_REF_NAME} \
            ${{ steps.vars.outputs.sha }}
