name: build-and-push

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: web
            context: .
            dockerfile: ./Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/gy-web

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          IMG="${{ matrix.image }}"
          SHA_TAG="${IMG}:${GITHUB_SHA}"
          LATEST_TAG="${IMG}:latest"
          BRANCH_TAG="${IMG}:branch-${GITHUB_REF_NAME//\//-}"
          echo "sha=${SHA_TAG}"   >> $GITHUB_OUTPUT
          echo "latest=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.vars.outputs.sha }}
            ${{ steps.vars.outputs.latest }}
            ${{ steps.vars.outputs.branch }}
          cache-from: type=registry,ref=${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=${{ matrix.image }}:buildcache,mode=max

      - name: Also tag release (if tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx imagetools create -t ${{ matrix.image }}:${GITHUB_REF_NAME} \
            ${{ steps.vars.outputs.sha }}
